### ISSUE TITLE
kicking players

### ISSUE THREAD

**Issue by SrMonsterYT** [NEZNAMY/TAB-Bridge#34] opened 2024-04-30 18:27 UTC
i'm using velocity, when i connect to the server i get kicked, when i remove the TAB-Bridge, the kick doesn't happen

TAB-Bridge.v5.0.6

server version:  version git-Pufferfish-49 (MC: 1.20.4)
velocity: 3.3.0-SNAPSHOT (git-399bc232-b386)

plugins: https://prnt.sc/ZNmSLIRky8_9

error: network protocol error

**Comment by NEZNAMY** [comment] 2024-04-30 18:52
Send the error from client log.

**Comment by SrMonsterYT** [comment] 2024-04-30 18:55
> Send the error from client log.

i get nothing, only when i enter i get kicked and the error appears on the screen, in the console there is no error

**Comment by SrMonsterYT** [comment] 2024-04-30 19:14
> Send the error from client log.

when i deactivate the scoreboard the problem is solved!

**Comment by NEZNAMY** [comment] 2024-05-01 08:22
What's the point of tagging me? I am responding as soon as I am online, tagging me won't do anything. I also bet you didn't enable client console, because an error **is** printed every time client disconnects with that error.

**Comment by SrMonsterYT** [comment] 2024-05-01 17:26
> What's the point of tagging me? I am responding as soon as I am online, tagging me won't do anything. I also bet you didn't enable client console, because an error **is** printed every time client disconnects with that error.
> 
> Another thing you can do is create a test network with only TAB, reproduce it there and then zip all 3 servers and upload them, so I can download it and try with your identical setup.

I discovered another problem, when I'm on 1.20.4, and I enter the server with TAB-Bridge I don't get kicked, but when I enter version 1.20.6 I get kicked

**Comment by SrMonsterYT** [comment] 2024-05-02 11:57
> Your discovery is already described in my first comment in the first issue, where I clearly said mojang added it in 1.20.5.
> 
> You **still** did not enable client console to send logs from it and **still** did not provide a test setup to reproduce it on.

my config: https://mclo.gs/ttfjts0
logs: https://mclo.gs/TnqEiK3

I don't understand what you mean by "enable client"

**Comment by NEZNAMY** [comment] 2024-05-02 16:17
You keep sending server logs. I am asking for client logs.

**Comment by SrMonsterYT** [comment] 2024-05-02 18:41
> You keep sending server logs. I am asking for client logs.

client logs: https://mclo.gs/ohHpVI1

**Comment by NEZNAMY** [comment] 2024-05-02 18:57
I wasn't able to reproduce this issue. Please create a test network with only TAB and bridge and then upload the setup, so I download it and try.

**Comment by SrMonsterYT** [comment] 2024-05-03 12:50
> I wasn't able to reproduce this issue. Please create a test network with only TAB and bridge and then upload the setup, so I download it and try.

i deleted the folder and configured everything from scratch, then when i set it to bungeecord the error occurs, that's my configuration causing the problem: https://mclo.gs/ATSlMb0

when I put

scoreboard:
  enabled: false

the problem is over, I just need to deactivate the scoreboard and the error doesn't occur

**Comment by NEZNAMY** [comment] 2024-05-03 14:20
BungeeCord? Bridge only sends screboards through bridge on Velocity.

Once again, make a test network setup with only TAB and bridge, reproduce it there, zip all servers and upload them somewhere, so I can try with the identical setup.

**Comment by SrMonsterYT** [comment] 2024-05-03 14:26
> BungeeCord? Bridge only sends screboards through bridge on Velocity.
> 
> Once again, make a test network setup with only TAB and bridge, reproduce it there, zip all servers and upload them somewhere, so I can try with the identical setup.

bungeecord I mean the name of the server, it's velocity the jar, do you want me to send you all the servers?
how do i get onto a 1.20.4 server without viaversion?

**Comment by NEZNAMY** [comment] 2024-05-03 14:35
Then add ViaVersion with addons as well. Once you reproduce the issue, upload all the servers and send them.

**Comment by NEZNAMY** [comment] 2024-05-03 18:42
Your issue was already fixed in dev builds of TAB a week ago.

**Comment by hervidero** [comment] 2024-05-03 19:48
Had the same/similar issue after updating our servers today. Can confirm that using a DEV build (4.15-snapshot build #1119) of the TAB plugin on the velocity server fixes the issue. (No need to update TAB-Bridge)

**Closed** 2024-05-08 14:47 UTC
